- update workflows/ci-cd-k6-scalability-test.yml

diff --git a/.github/workflows/ci-cd-k6-scalability-test.yml b/.github/workflows/ci-cd-k6-scalability-test.yml
--- a/.github/workflows/ci-cd-k6-scalability-test.yml
+++ b/.github/workflows/ci-cd-k6-scalability-test.yml
@@ -313,69 +313,67 @@ jobs:
           # execute k6 test
           # k6 run $K6_TEST_FILE
           # available output types: cloud (maybe charged fee), csv, experimental-opentelemetry, experimental-prometheus-rw, influxdb, json, opentelemetry, statsd, web-dashboard
-          (
-            if [ "$K6_RPT_TYPE" == "console" ]; then
-              k6 run $K6_TEST_FILE
+          if [ "$K6_RPT_TYPE" == "console" ]; then
+            k6 run $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "prometheus" ]; then
+            # ⚙️ Calculate and encode AUTHORIZATION HEADER by BASIC AUTH STANDARDS
+            RAW_AUTH="${{ secrets.GRAFANA_USER_ID }}:${{ secrets.GRAFANA_API_TOKEN }}"
+            ENCODED_AUTH=$(printf "%s" "$RAW_AUTH" | base64 | tr -d '\n\r')
+            export K6_OTEL_HEADERS="Authorization=Basic $ENCODED_AUTH"
+            export GRACEFUL_STOP=5 # keep k6 waiting for pushing metrics finished
             
-            elif [ "$K6_RPT_TYPE" == "prometheus" ]; then
-              # ⚙️ Calculate and encode AUTHORIZATION HEADER by BASIC AUTH STANDARDS
-              RAW_AUTH="${{ secrets.GRAFANA_USER_ID }}:${{ secrets.GRAFANA_API_TOKEN }}"
-              ENCODED_AUTH=$(printf "%s" "$RAW_AUTH" | base64 | tr -d '\n\r')
-              export K6_OTEL_HEADERS="Authorization=Basic $ENCODED_AUTH"
-              export GRACEFUL_STOP=5 # keep k6 waiting for pushing metrics finished
-              
-              k6 run \
-                --out opentelemetry \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "otlp" ]; then
-              k6 run \
-                --out opentelemetry \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "experimental-otlp" ]; then
-              k6 run \
-                --out experimental-opentelemetry \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "influxdb" ]; then
-              k6 run \
-                --out influxdb=http://localhost:8086/k6-test-report \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "datadog" ]; then
-              k6 run \
-                --out statsd \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "json" ]; then
-              k6 run \
-                --out json=k6-test-report.json \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "csv" ]; then
-              k6 run \
-                --out csv=k6-test-report.csv \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            elif [ "$K6_RPT_TYPE" == "web-dashboard" ]; then
-              k6 run \
-                --out web-dashboard=report=k6-test-report.html \
-                --tag test_env=seats-reservation-k6-test \
-                $K6_TEST_FILE
-            
-            else
-              echo "❌ [ $K6_RPT_TYPE | $K6_RPT_TYPE_NAME ] is an UNSUPPORTED report type."
-              exit 100 # break pipeline via k6 exit code
-            fi
-          )
+            k6 run \
+              --out opentelemetry \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "otlp" ]; then
+            k6 run \
+              --out opentelemetry \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "experimental-otlp" ]; then
+            k6 run \
+              --out experimental-opentelemetry \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "influxdb" ]; then
+            k6 run \
+              --out influxdb=http://localhost:8086/k6-test-report \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "datadog" ]; then
+            k6 run \
+              --out statsd \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "json" ]; then
+            k6 run \
+              --out json=k6-test-report.json \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "csv" ]; then
+            k6 run \
+              --out csv=k6-test-report.csv \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          elif [ "$K6_RPT_TYPE" == "web-dashboard" ]; then
+            k6 run \
+              --out web-dashboard=report=k6-test-report.html \
+              --tag test_env=seats-reservation-k6-test \
+              $K6_TEST_FILE
+          
+          else
+            echo "❌ [ $K6_RPT_TYPE | $K6_RPT_TYPE_NAME ] is an UNSUPPORTED report type."
+            exit 100 # break pipeline via k6 exit code
+          fi
           
           # receive k6 test exit code to check
           K6_EXIT_CODE=$?
