- upload workflows/ci-cd-gke-deploy.yml + publish GKE URL to README

diff --git a/.github/workflows/ci-cd-gke-deploy.yml b/.github/workflows/ci-cd-gke-deploy.yml
--- a/.github/workflows/ci-cd-gke-deploy.yml
+++ b/.github/workflows/ci-cd-gke-deploy.yml
@@ -647,6 +647,7 @@ jobs:
       # 14. Check deployment status
       - name: 📊 Check Rollout Status & Extract Deployment Metadata
         if: success()                 # if previous step is successful
+        id: gke_cloud_run_deployment_check
         env:
           K8S_DEPLOYMENT_NAMESPACE: ${{ matrix.service.env_vars.K8S_DEPLOYMENT_NAMESPACE }}
           K8S_DEPLOYMENT_NAME: ${{ matrix.service.env_vars.K8S_DEPLOYMENT_NAME }}
@@ -718,6 +719,7 @@ jobs:
           echo "📜 5. CALCULATE THE GKE PUBLIC URL"
           echo "========================================================================="
           # Calculate if after delay time, and could not get the external IP (Ex: GKE Hardware Stuck)
+          PUBLIC_URL=""
           if [ -z "$EXTERNAL_IP" ] || [ "$EXTERNAL_IP" == "<pending>" ] || [ "$EXTERNAL_IP" == "<none>" ]; then
             echo "::warning::⚠️ GCP LoadBalancer failed to allocate a public IP within $TIMEOUT. Retry once more time to detect the GKE Public URL."
           
@@ -735,6 +737,96 @@ jobs:
             echo "* **Kubernetes Room (Namespace):** \`$K8S_DEPLOYMENT_NAMESPACE\`" >> $GITHUB_STEP_SUMMARY
             echo "* **Clickable Production Endpoint Link:** [$PUBLIC_URL]($PUBLIC_URL)" >> $GITHUB_STEP_SUMMARY
           fi
+          echo "gke_cloud_run_url=$PUBLIC_URL" >> $GITHUB_OUTPUT
+      
+      # 15. Save service published information to an temporary artifact for next step
+      - name: 💾 Save Service URL to Temp File
+        if: success()                 # if previous step is successful
+        run: |
+          # create a JSON file to keep the published information
+          echo '{"name": "gke-${{ matrix.service.name }}", "published_url": "${{ steps.gke_cloud_run_deployment_check.outputs.gke_cloud_run_url }}"}' > "gke-${{ matrix.service.name }}.json"
+      
+      # 15.1. Upload published service JSON to an temporary artifact
+      - name: 📦 Upload Published Service Information Artifact
+        if: success()                 # if previous step is successful
+        uses: actions/upload-artifact@v4
+        with:
+          # Unique artifact name by service to avoid conflicted/overwritten
+          name: gke-url-${{ matrix.service.name }}
+          path: "gke-${{ matrix.service.name }}.json"
+  
+  # ==============================================================================
+  # 🛠️ COMBINE PUBLISHED URL(s) BY SERVICE
+  # ==============================================================================
+  combine-published-urls-by-service:
+    name: 🌐 Combine Published URL(s) to update README.md
+    runs-on: ubuntu-latest
+    needs: [ deploy-to-gcp ]                        # wait for deployment
+    
+    # output for next job
+    outputs:
+      published-services: ${{ steps.build_published_services.outputs.published-services }}
+    
+    steps:
+      # 1. Download Published Service Information Artifact from previous job to combine
+      - name: 📥 Download All Service Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          # Use pattern (*) to download all artifacts with prefix `gke-url-` to same folder
+          pattern: gke-url-*
+          path: temp-gke-urls
+          merge-multiple: true # Merge all files `.json` to `temp-gke-urls` folder
+      
+      # 2. Read artifact folder to combine published information
+      - name: 🛠️ Combine Published URL(s) to Enviroment JSON Variables
+        id: build_published_services
+        run: |
+          echo "1. Artifact JSON files:"
+          ls -la temp-gke-urls/
+          
+          echo "----------------------------------------"
+          echo "2. Combine all JSON files..."
+          # Check if not found any json file
+          if [ ! -d "temp-gke-urls" ] || [ -z "$(ls -A temp-gke-urls/gke-*.json 2>/dev/null)" ]; then
+            echo "❌ Not found any published information `.json` file."
+            exit 1
+          fi
+          
+          # Use `jq` to read all `.json` file and collect to JSON array
+          PUBLISHED_SERVICES=$(jq -s -c '.' temp-gke-urls/gke-*.json)
+          echo "🏃 Published Services:"
+          echo "$PUBLISHED_SERVICES"
+          echo "published-services=$PUBLISHED_SERVICES" >> $GITHUB_OUTPUT
+  
+  # ==============================================================================
+  # ⚡ PUBLISH URL TO README
+  # ==============================================================================
+  publish-url-to-readme:
+    name: ⚡ Generate and Export GCP/GKE Links to README
+    needs: [ deploy-to-gcp, combine-published-urls-by-service ]           # wait for deployment, combine enviroment
+    secrets: inherit # bypass secrets to child workflow
+    uses: ./.github/workflows/ci-cd-publish-url.yml
+    with:
+      env_data: ${{ needs.combine-published-urls-by-service.outputs.published-services }}
+  
+  # ==============================================================================
+  # ⚙️ CLEAN UP
+  # ==============================================================================
+  clean-up:
+    name: ⚙️ Force Kill Orphan Processes
+    runs-on: ubuntu-latest
+    needs: [ deploy-to-gcp, publish-url-to-readme ]           # wait for deployment, combine enviroment
+    # always run although other jobs are success or failure
+    if: ${{ !cancelled() }}
+    
+    steps:
+      # Clean up temporary artifact
+      - name: 🧹 Clean up Temp Artifacts from GitHub Storage
+        if: always()    # Always run to clean up
+        uses: geekyeggo/delete-artifact@v5
+        with:
+          # Use pattern (*) to delete all artifacts with prefix `gke-url-`
+          name: gke-url-*
       
       # Clean up
       - name: ⚙️ Force Kill Orphan Processes
