- update workflows/ci-cd-k6-scalability-test.yml

diff --git a/.github/workflows/ci-cd-k6-scalability-test.yml b/.github/workflows/ci-cd-k6-scalability-test.yml
--- a/.github/workflows/ci-cd-k6-scalability-test.yml
+++ b/.github/workflows/ci-cd-k6-scalability-test.yml
@@ -33,12 +33,12 @@ on:
           - 🌿 GitHub CI/CD Console
           - 🔣 JSON
           - 🔢 CSV
-          - 🕸️ Web Dashboard [ Port 5665 ]
+          - 🕸️ Web Dashboard
           - 🔥 Prometheus
           - 📊 OTLP
           - 👣 Experimental OTLP
-          - 🔭 Time-Series Database InfluxDB [ Port 8086 ]
-          - 📝 StatsD, Datadog Agent, or New Relic
+          - 🔭 Time-Series Database InfluxDB
+          - 📝 Datadog Agent
   
   # allow other workflow call into (inputs same as workflow_dispatch but required)
   workflow_call:
@@ -71,12 +71,12 @@ on:
           - 🌿 GitHub CI/CD Console
           - 🔣 JSON
           - 🔢 CSV
-          - 🕸️ Web Dashboard [ Port 5665 ]
-          - 🔥 Prometheus: Metrics Collecting
+          - 🕸️ Web Dashboard
+          - 🔥 Prometheus
           - 📊 OTLP
           - 👣 Experimental OTLP
-          - 🔭 Time-Series Database InfluxDB [ Port 8086 ]
-          - 📝 StatsD, Datadog Agent, or New Relic
+          - 🔭 Time-Series Database InfluxDB
+          - 📝 Datadog Agent
 
 # permissions for GitHub Actions READ/WRITE
 permissions:
@@ -111,6 +111,61 @@ jobs:
       - name: 📁 Checkout Benchmark Engineering Repositories
         if: success()                 # if previous step is successful
         uses: actions/checkout@v4
+      
+      # 2.1 Optional: for InfluxDB metrics report
+      - name: 🐋 Spin Up Isolated Docker InfluxDB Substrate Server
+        if: success() && (inputs.k6_test_report == '🔭 Time-Series Database InfluxDB')
+        run: |
+          echo "Bootstrapping containerized InfluxDB storage node..."
+          # Use InfluxDB 1.8 port 8086
+          docker run -d \
+            -p 8086:8086 \
+            --name local-influxdb-agent \
+            influxdb:1.8
+          
+          # wait 5 seconds for container starting in RAM
+          sleep 5
+          
+          # create a internal db to save metrics report - k6-test-report
+          docker exec local-influxdb-agent influx -execute "CREATE DATABASE k6-test-report"
+          echo "✅ InfluxDB Docker infrastructure established successfully at port 8086."
+      
+      # 2.2 Optional: for Datadog Agent
+      - name: 🐋 Spin Up Local Vector Agent Node (Absolute Offline)
+        if: success() && (inputs.k6_test_report == '📝 Datadog Agent')
+        run: |
+          echo "Bootstrapping containerized Vector Agent logging substrate..."
+          
+          # create light datadog config file in RAM to control datadog vector:
+          # "open port 8125 to receive k6, after that export to file /tmp/vector-output.json"
+          mkdir -p ./vector-config
+          cat << 'EOF' > ./vector-config/vector.yaml
+          sources:
+            k6_statsd:
+              type: "statsd"
+              address: "0.0.0.0:8125"
+              mode: "udp"
+          
+          sinks:
+            physical_file_export:
+              type: "file"
+              inputs: ["k6_statsd"]
+              path: "/tmp/vector-output.json"
+              encoding:
+                codec: "json"
+          EOF
+          
+          # run Container Vector Local Docker, mount folder config and ouput folder
+          docker run -d \
+            -p 8125:8125/udp \
+            --name vector-local-agent \
+            -v $(pwd)/vector-config:/etc/vector:ro \
+            -v $(pwd)/perf-reports:/tmp \
+            timberio/vector:0.30.X-debian
+          
+          # wait 3 seconds for container starting in RAM
+          sleep 3
+          echo "✅ Local Vector Agent established successfully. DogStatsD pipeline listening at UDP port 8125."
       
       # 3. Set-up native k6 engine to test
       - name: ⚙️ Setup Native k6 Binary Engine on Runner Node
@@ -169,13 +224,13 @@ jobs:
               --tag test_env=seats-reservation-k6-test \
               $K6_TEST_FILE
           
-          elif [ "$K6_RPT_TYPE" == "🔭 Time-Series Database InfluxDB [ Port 8086 ]" ]; then
+          elif [ "$K6_RPT_TYPE" == "🔭 Time-Series Database InfluxDB" ]; then
             k6 run \
-              --out influxdb \
+              --out influxdb=http://localhost:8086/k6-test-report \
               --tag test_env=seats-reservation-k6-test \
               $K6_TEST_FILE
           
-          elif [ "$K6_RPT_TYPE" == "📝 StatsD, Datadog Agent, or New Relic" ]; then
+          elif [ "$K6_RPT_TYPE" == "📝 Datadog Agent" ]; then
             k6 run \
               --out statsd \
               --tag test_env=seats-reservation-k6-test \
@@ -195,9 +250,10 @@ jobs:
               --tag test_env=seats-reservation-k6-test \
               $K6_TEST_FILE
           
-          elif [ "$K6_RPT_TYPE" == "🕸️ Web Dashboard [ Port 5665 ]" ]; then
+          elif [ "$K6_RPT_TYPE" == "🕸️ Web Dashboard" ]; then
+            echo "$K6_RPT_TYPE: Report JSON file 'k6-test-report.html' will be exported after testing finished"
             k6 run \
-              --out web-dashboard \
+              --out web-dashboard=report=k6-test-report.html \
               --tag test_env=seats-reservation-k6-test \
               $K6_TEST_FILE
           
@@ -206,9 +262,41 @@ jobs:
             exit 1
           fi
       
+      # 4.1 Optional: for InfluxDB metrics report
+      - name: 🗜️ Execute InfluxDB Telemetry Data Export Protocol
+        if: always() && (inputs.k6_test_report == '🔭 Time-Series Database InfluxDB')
+        run: |
+          echo "Extracting raw time-series data chunks from docker container ecosystem..."
+          
+          # use influxd backup tool in container to compress db output to temporary folder
+          docker exec local-influxdb-agent influxd backup -database k6-test-report /tmp/k6-test-report
+          
+          # copy file backup from Container Docker to Runner VM
+          docker cp local-influxdb-agent:/tmp/k6-test-report ./k6-influxdb-exported-data
+          
+          # compress exported folder backup to file .tar.gz for downloading
+          tar -czvf k6-test-report.tar.gz ./k6-influxdb-exported-data
+          echo "✅ Telemetry data exported and compressed successfully into k6-test-report.tar.gz"
+      
+      # 4.2 Optional: for Datadog Agent
+      - name: 🗜️ Process and Compact Vector Exported Telemetry File
+        if: always() && (inputs.k6_test_report == '📝 Datadog Agent')
+        run: |
+          echo "Validating offline telemetry logs captured on local storage substrate..."
+          
+          # validate file json by Vector already existed
+          if [ -f "./perf-reports/vector-output.json" ]; then
+            echo "✅ Telemetry file captured successfully!"
+            # compress to file .tar.gz for downloading
+            tar -czvf k6-test-report.tar.gz -C ./perf-reports vector-output.json
+          else
+            echo "🚨 [Critical Error]: Vector Agent failed to write telemetry logs on disk."
+            exit 1
+          fi
+      
       # 5. Upload report files to artifact for downloading
       - name: 📦 Archive Performance Telemetry Artifacts for Download
-        if: success() && (inputs.k6_test_report == '🔣 JSON' || inputs.k6_test_report == '🔢 CSV')
+        if: success() && (inputs.k6_test_report == '🔣 JSON' || inputs.k6_test_report == '🔢 CSV' || inputs.k6_test_report == '🕸️ Web Dashboard' || inputs.k6_test_report == '🔭 Time-Series Database InfluxDB' || inputs.k6_test_report == '📝 Datadog Agent')
         uses: actions/upload-artifact@v4
         with:
           name: k6-test-reports     # report file ZIP name
@@ -227,7 +315,7 @@ jobs:
           echo "* **Sustained Load Blast Window:** \`${{ inputs.test_duration }}\`" >> $GITHUB_STEP_SUMMARY
           echo "✅ Execution metrics maps registered. Check the step logs above to review raw telemetry latency data table!" >> $GITHUB_STEP_SUMMARY
           echo "✅ Real-time metrics streaming process executed flawlessly. Grafana dashboard telemetry stack ready for export." >> $GITHUB_STEP_SUMMARY
-          if [ "$K6_RPT_TYPE" = "🔣 JSON" -o "$K6_RPT_TYPE" = "🔢 CSV" ]; then
+          if [ "$K6_RPT_TYPE" = "🔣 JSON" -o "$K6_RPT_TYPE" = "🔢 CSV" -o "$K6_RPT_TYPE" = "🕸️ Web Dashboard" -o "$K6_RPT_TYPE" = "🔭 Time-Series Database InfluxDB" -o "$K6_RPT_TYPE" = "📝 Datadog Agent" ]; then
             echo "✅ Raw test data successfully captured. Navigate to the top of this Workflow run summary page to download **k6-test-reports.zip**!" >> $GITHUB_STEP_SUMMARY
           fi
       
