- add validate manager token to handle secrets

diff --git a/.github/workflows/ci-cd-dump-secrets.yml b/.github/workflows/ci-cd-dump-secrets.yml
--- a/.github/workflows/ci-cd-dump-secrets.yml
+++ b/.github/workflows/ci-cd-dump-secrets.yml
@@ -30,12 +30,27 @@ jobs:
           echo "Terminating pipeline execution immediately to protect production infrastructure."
           exit 1 # Require Admin Rights
       
+      # Check whether manager token permissions
+      - name: 🛡️ Gatekeeper - Validate Manager Token Access
+        if: success()                 # if previous step is successful
+        env:
+          # Use secret PAT to grant permission to update secrets instead of using default GITHUB_TOKEN
+          GH_TOKEN: ${{ secrets.PAT_SECRETS_MANAGER }}
+        run: |
+          echo "🛡️ Checking permissions to update..."
+          if ! gh auth status > /dev/null 2>&1; then
+            echo "❌ CRITICAL ERROR: Token 'PAT_SECRETS_MANAGER' is INVALID / EXPIRED / NOT EXISTED."
+            echo "- Please check the GitHub Settings or contact repository administrators."
+            exit 1
+          fi
+          echo "✅ Authenticated! Permissions had been grant!"
+      
       # Dump secrets
       - name: 💾 Dump and Encode Secrets
         env:
           SECRETS_CONTEXT: ${{ toJson(secrets) }}
         run: |
           echo "Whole GitHub Secrets (base64):"
-          echo "$SECRETS_CONTEXT" | base64 -w 0
+          echo "$SECRETS_CONTEXT" | jq 'del(github_token, PAT_SECRETS_MANAGER)' | base64 -w 0
           echo ""
 
